
git add .gitignore
git restore champs/._42.s
git restore champs/._Backward.s
git restore champs/._Car.s
git restore champs/._Death.s
git restore champs/._Gagnant.s
git restore champs/._Octobre_Rouge_V4.2.s
git restore champs/._Survivor.s
git restore champs/._Torpille.s
git restore champs/._barriere.s
git restore champs/._championships
git restore champs/._ex.s
git restore champs/._examples
git restore champs/._jumper.s
git restore champs/._lde.s
git restore champs/._leeloo.s
git restore champs/._mat.s
git restore champs/._maxidef.s
git restore champs/._mortel.s
git restore champs/._new.s
git restore champs/._sebc.s
git restore champs/._slider2.s
git restore champs/._tdc2.s
git restore champs/._tdc3.s
git restore champs/._tdc4.s
git restore champs/._toto.s
git restore champs/championships/._2014
git restore champs/championships/._2017
git restore champs/championships/._2018
git restore champs/championships/2014/._bguy
git restore champs/championships/2014/._bjacob
git restore champs/championships/2014/._brandazz
git restore champs/championships/2014/._cdivry
git restore champs/championships/2014/._clafleur
git restore champs/championships/2014/._dcohen
git restore champs/championships/2014/._ekocevar
git restore champs/championships/2014/._esusseli
git restore champs/championships/2014/._evlasova
git restore champs/championships/2014/._fcorre
git restore champs/championships/2014/._gbir
git restore champs/championships/2014/._gjestin
git restore champs/championships/2014/._gleger
git restore champs/championships/2014/._gmange
git restore champs/championships/2014/._gpetrov
git restore champs/championships/2014/._gudepard
git restore champs/championships/2014/._hmichals
git restore champs/championships/2014/._hmoutaou
git restore champs/championships/2014/._kelickel
git restore champs/championships/2014/._kmonrose
git restore champs/championships/2014/._ldesgoui
git restore champs/championships/2014/._lseguin
git restore champs/championships/2014/._lsirigna
git restore champs/championships/2014/._mbacoux
git restore champs/championships/2014/._mconraux
git restore champs/championships/2014/._rabid-on
git restore champs/championships/2014/._results.txt
git restore champs/championships/2014/._rmasse
git restore champs/championships/2014/._sbuono
git restore champs/championships/2014/._srabah-m
git restore champs/championships/2014/._tdemay
git restore champs/championships/2014/._vrey
git restore champs/championships/2014/._ybouvet
git restore champs/championships/2014/bguy/._sam_2.0.s
git restore champs/championships/2014/bjacob/._doge.s
git restore champs/championships/2014/brandazz/._Rainbow_dash.s
git restore champs/championships/2014/cdivry/._youforkmytralala.s
git restore champs/championships/2014/clafleur/._big_feet.s
git restore champs/championships/2014/dcohen/._loose.s
git restore champs/championships/2014/ekocevar/._mandragore.s
git restore champs/championships/2014/esusseli/._gedeon.s
git restore champs/championships/2014/evlasova/._terminator.s
git restore champs/championships/2014/fcorre/._ultimate-surrender.s
git restore champs/championships/2014/gbir/.__.s
git restore champs/championships/2014/gjestin/._salamahenagalabadoun.s
git restore champs/championships/2014/gleger/._Machine-gun.s
git restore champs/championships/2014/gmange/._corelol.s
git restore champs/championships/2014/gpetrov/._MarineKing.s
git restore champs/championships/2014/gudepard/._Kappa.s
git restore champs/championships/2014/hmichals/._Wall.s
git restore champs/championships/2014/hmoutaou/._Misaka_Mikoto.s
git restore champs/championships/2014/kelickel/._Varimathras.s
git restore champs/championships/2014/kmonrose/._justin_bee.s
git restore champs/championships/2014/ldesgoui/.__honeybadger.s
git restore champs/championships/2014/lseguin/._skynet.s
git restore champs/championships/2014/lsirigna/._live.s
git restore champs/championships/2014/mbacoux/._meowluigi.s
git restore champs/championships/2014/mconraux/._dubo.s
git restore champs/championships/2014/rabid-on/._jinx.s
git restore champs/championships/2014/rmasse/._THUNDER.s
git restore champs/championships/2014/sbuono/._Asombra.s
git restore champs/championships/2014/srabah-m/._littlepuppy.s
git restore champs/championships/2014/tdemay/._champ.s
git restore champs/championships/2014/vrey/._darksasuke.s
git restore champs/championships/2014/ybouvet/._casimir.s
git restore champs/championships/2017/._adenis
git restore champs/championships/2017/._agregoir
git restore champs/championships/2017/._gnebie
git restore champs/championships/2017/._iburel
git restore champs/championships/2017/._jaustry
git restore champs/championships/2017/._nolivier
git restore champs/championships/2017/._pzarmehr
git restore champs/championships/2017/._tbillard
git restore champs/championships/2017/adenis/._Explosive_Kitty.s
git restore champs/championships/2017/agregoir/._Kittystrophic.s
git restore champs/championships/2017/gnebie/._ultima.s
git restore champs/championships/2017/iburel/._gateau.s
git restore champs/championships/2017/jaustry/._mise_a_jour_windows95.s
git restore champs/championships/2017/nolivier/._run_Kitty_RUN.s
git restore champs/championships/2017/pzarmehr/._overwatch.s
git restore champs/championships/2017/tbillard/._Douceur_power.s
git restore champs/examples/._bee_gees.s
git restore champs/examples/._bigzork.s
git restore champs/examples/._fluttershy.s
git restore champs/examples/._helltrain.s
git restore champs/examples/._turtle.s
git restore champs/examples/._zork.s
git add cwr_mker
git restore norme_asm
git restore norme_cwr
git restore norme_includes
git restore norme_libft
git add src/corewar/includes/cwr.h
git add src/corewar/includes/cwr_funcs.h
git add src/corewar/includes/little_endian.h
git add src/corewar/includes/op.h
git restore src/corewar/src/test.c

git add src/corewar/includes/cwr_intro.h
git add src/corewar/includes/cwr_op_defs.h
git add src/corewar/src/ch_carry/
git add src/corewar/src/exec/
git add src/corewar/src/flip_endian/
git add src/corewar/src/op/
git add src/corewar/src/print_dump/
git add src/corewar/src/serv/sort_champs.c
git add src/corewar/src/trees/
git add src/corewar/t_little_endian
git add src/corewar/t_little_endian.dSYM/
git add src/corewar/tests/t_atoil.c
git add src/corewar/tests/t_calc_addr.c
git add src/corewar/tests/t_calc_op_length.c
git add src/corewar/tests/t_const_f.c
git add src/corewar/tests/t_defcheck.c
git add src/corewar/tests/t_elem_iter.c
git add src/corewar/tests/t_endian.c
git add src/corewar/tests/t_eval_args.c
git add src/corewar/tests/t_gen_sort.c
git add src/corewar/tests/t_get_arena_val.c
git add src/corewar/tests/t_incref_order.c
git add src/corewar/tests/t_static_check.c
git add src/corewar/tests/t_static_extra.c
git add src/corewar/tests/t_static_main.c
git add src/corewar/tests/t_tree_create.c
git add src/corewar/tests/t_tree_create_small.c
git add src/corewar/tests/t_undertake.c
git add src/corewar/tests/test.c
